-- =====================================================================
--  Impression 3D — schéma à coller dans le SQL Editor de Supabase
--  (MÊME projet que reservation-machines : ggmlfbxppgeivfvlxxrj)
--
--  Ce script AJOUTE deux tables (demandes, parametres) et quelques colonnes aux tables
--  existantes etudiants (formation, encadrant3) et bookings (encadrant3, pour l'appli
--  Usinage). Il ne supprime ni ne modifie aucune donnée existante.
--  On peut le relancer sans risque (IF NOT EXISTS partout).
-- =====================================================================

-- ---------- Table des demandes d'impression --------------------------
create table if not exists public.demandes (
  id                  bigint generated by default as identity primary key,
  created_at          timestamptz not null default now(),
  etudiant_nom        text not null default '',
  etudiant_prenom     text not null default '',
  projet              text not null default '',
  fichier_nom         text not null default '',
  drive_file_id       text default '',
  drive_link          text default '',
  machine             text not null default 'bambulab',   -- bambulab | markforged
  volume_mm3          double precision default 0,
  bbox                text default '',                      -- "LxLxH mm"
  temps_estime_min    integer default 0,
  temps_final_min     integer default 0,
  statut              text not null default 'en_attente',  -- en_attente|validee|refusee|en_cours|imprimee
  encadrant_nom       text default '',
  encadrant_valide_at timestamptz,
  imprime_at          timestamptz,
  notes               text default '',                   -- commentaire de l'étudiant
  numero              integer default 0,                 -- n° incrémental par projet
  taraudage           boolean default false,
  insert_filete       boolean default false,
  usinage             boolean default false,
  finition            text default 'brouillon',          -- brouillon | finition
  temps_categorie     text default '',                   -- "moins de 3h" ...
  encadrant_commentaire text default ''
);

-- Colonnes ajoutées après coup (pour une base déjà créée : relançable sans risque)
alter table public.demandes add column if not exists numero               integer default 0;
alter table public.demandes add column if not exists taraudage            boolean default false;
alter table public.demandes add column if not exists insert_filete        boolean default false;
alter table public.demandes add column if not exists usinage              boolean default false;
alter table public.demandes add column if not exists finition             text default 'brouillon';
alter table public.demandes add column if not exists temps_categorie      text default '';
alter table public.demandes add column if not exists encadrant_commentaire text default '';
alter table public.demandes add column if not exists en_cours_at          timestamptz;
alter table public.demandes add column if not exists duree_reelle_min     integer default 0;
alter table public.demandes add column if not exists operateur_nom        text default '';
alter table public.demandes add column if not exists archive              boolean default false;  -- demande archivée (retirée du tableau opérateur)
alter table public.demandes add column if not exists priorite             integer default 0;      -- ordre dans la file d'attente d'impression
alter table public.demandes add column if not exists photo_file_id        text default '';        -- ID Drive de la photo de la pièce terminée
alter table public.demandes add column if not exists photo_link           text default '';        -- lien Drive de la photo de la pièce terminée

-- Index pour le suivi étudiant (recherche par nom/prénom) et les listes
create index if not exists demandes_statut_idx  on public.demandes (statut);
create index if not exists demandes_etudiant_idx on public.demandes (lower(etudiant_nom), lower(etudiant_prenom));

-- Colonnes ajoutées à la table etudiants (gestion depuis la page d'accueil) :
-- formation de l'étudiant (2A, 2I, 3A...) et 3e encadrant possible.
alter table public.etudiants add column if not exists formation  text default '';
alter table public.etudiants add column if not exists encadrant3 text default '';
create index if not exists demandes_projet_idx   on public.demandes (projet);

-- Colonne ajoutée à la table bookings (Réservation Machines / usinage) : le 3e encadrant
-- d'un projet est désormais aussi affiché/rempli automatiquement lors d'une réservation.
alter table public.bookings add column if not exists encadrant3 text default '';

-- ---------- Table des paramètres (clé / valeur) ----------------------
create table if not exists public.parametres (
  cle    text primary key,
  valeur text not null default ''
);

-- Valeurs par défaut (ne réécrase pas si déjà présentes)
insert into public.parametres (cle, valeur) values
  ('code_encadrant', '0000'),   -- code partagé de validation encadrant
  ('limite_defaut',  '10'),     -- limite d'impressions par projet (par défaut)
  ('limites_projets','{}'),     -- surcharges par projet (gérées par l'opérateur)
  -- Machines proposées (gérées en admin) : débit mm³/min, temps fixe min, taux de remplissage 0-1
  ('machines', '[{"nom":"Bambu Lab","emoji":"🟢","debit":300,"overhead":10,"taux":0.35,"desc":"FDM rapide — plastique"},{"nom":"Markforged","emoji":"🔵","debit":120,"overhead":15,"taux":0.35,"desc":"Composite renforcé"}]')
on conflict (cle) do nothing;

-- ---------- Sécurité (RLS) : accès anon, comme le reste de l'appli ---
alter table public.demandes   enable row level security;
alter table public.parametres enable row level security;

-- Demandes : lecture + insertion + mise à jour pour la clé anon
drop policy if exists demandes_all on public.demandes;
create policy demandes_all on public.demandes
  for all using (true) with check (true);

-- Paramètres : politique D'ORIGINE (avant la sécurisation par Edge Functions).
-- ⚠️ À NE PAS REJOUER TEL QUEL sur la base actuelle : « using (true) » rendrait la table
-- 'parametres' lisible directement par la clé anon (code_encadrant, et le hash admin dès
-- qu'il existe), court-circuitant la vue parametres_public. Depuis la sécurisation, toutes
-- les écritures passent par les Edge Functions (service role) et les applis lisent
-- uniquement la vue. Vérifier l'état réel avant toute recréation :
--   select tablename, policyname, cmd, qual from pg_policies where schemaname='public';
drop policy if exists parametres_all on public.parametres;
create policy parametres_all on public.parametres
  for all using (true) with check (true);

-- ---------- Contacts e-mail des demandes (VERROUILLÉ, RGPD) ---------------
-- Adresse e-mail facultative fournie par l'étudiant au dépôt, pour être prévenu quand sa pièce
-- est imprimée. Table SANS accès anon (aucune policy) : l'adresse n'est JAMAIS lisible par le
-- navigateur, seulement par les Edge Functions (demande-op pour l'écrire, notify-print-email pour
-- l'utiliser). L'adresse est supprimée après l'envoi du mail (minimisation). Suppression en cascade
-- si la demande est supprimée.
create table if not exists public.demande_contacts (
  demande_id bigint primary key references public.demandes(id) on delete cascade,
  email      text not null,
  created_at timestamptz not null default now()
);
alter table public.demande_contacts enable row level security;
-- (aucune policy volontairement : refus total pour anon)

-- ---------- Vues publiques (lecture anon) --------------------------------
-- Les applis ne lisent JAMAIS les tables 'operateurs' et 'parametres' directement :
-- elles passent par ces deux vues, qui n'exposent qu'un sous-ensemble sûr.
-- Les vues sont volontairement en SECURITY DEFINER (comportement par défaut d'une vue
-- Postgres) : c'est ce qui permet à la clé anon de les lire alors que les tables
-- sous-jacentes restent verrouillées. NE PAS passer en security_invoker : il faudrait
-- alors ouvrir les tables elles-mêmes à anon (codes opérateurs, hash admin) = pire.
-- L'advisor Supabase signale « Security Definer View » sur ces deux vues : faux positif
-- assumé, tant que les colonnes exposées restent celles ci-dessous.

-- Opérateurs : ni le code à 4 chiffres, ni le téléphone, ni la clé API ne sortent.
-- 'has_whatsapp' est un booléen CALCULÉ côté serveur (pas les valeurs).
create or replace view public.operateurs_public as
select name,
       notif_3d,
       coalesce(phone, '') <> '' and coalesce(apikey, '') <> '' as has_whatsapp,
       machines_outils,
       impression_3d
from public.operateurs;

-- Paramètres : LISTE D'AUTORISATION (et non d'exclusion). Ne jamais repasser à un
-- « where cle <> ALL (...) » : une nouvelle clé sensible fuiterait silencieusement.
-- C'est arrivé avec 'admin_pw_hash' (écrit par l'Edge Function admin-op quand le super
-- admin change le mot de passe) — corrigé en juillet 2026.
-- Ces 4 clés sont exactement celles que l'appli lit (loadParams / PARAMS.*).
create or replace view public.parametres_public as
select cle, valeur
from public.parametres
where cle in ('machines', 'limite_defaut', 'limites_projets', 'operateurs_impression');

grant select on public.operateurs_public to anon, authenticated;
grant select on public.parametres_public to anon, authenticated;

-- ---------- Realtime (rafraîchissement discret des écrans opérateur/encadrant/suivi) ---------
-- Ajoute les tables à la publication realtime si pas déjà fait (etudiants et operateurs
-- servent au rafraîchissement silencieux des listes projet/étudiant/opérateur).
do $$
begin
  begin alter publication supabase_realtime add table public.demandes;   exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.parametres; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.etudiants; exception when duplicate_object then null; end;
end $$;
