-- =====================================================================
--  Utilisation Matières — schéma à coller dans le SQL Editor de Supabase
--  (MÊME projet que reservation-machines / impression 3D / commandes : ggmlfbxppgeivfvlxxrj)
--
--  Ce script AJOUTE 10 tables (préfixe mat_). Il ne supprime ni ne modifie
--  aucune donnée ni aucune table existante. Relançable sans risque (IF NOT EXISTS).
--
--  Sécurité : lecture publique, écritures uniquement via l'Edge Function matiere-op (voir README.md).
-- =====================================================================

-- ---------- Matières (gérées par l'admin) ----------------------------
create table if not exists public.mat_matieres (
  nom        text primary key,                 -- ex. "Acier S235", "Aluminium 6060"
  densite    numeric not null default 7.85,    -- kg/dm³  (acier 7.85 · alu 2.70 · inox 7.9…)
  prix_kg    numeric,                          -- prix tel que saisi par l'admin (null = pas encore renseigné)
  prix_mode  text not null default 'ttc',      -- 'ttc' | 'ht' — le prix est TOUJOURS affiché/utilisé en TTC
  actif      boolean not null default true,
  maj_at     timestamptz not null default now()
);
alter table public.mat_matieres add column if not exists prix_mode text not null default 'ttc';

-- ---------- Fournisseurs (gérés par l'admin) ---------------------------
create table if not exists public.mat_fournisseurs (
  nom        text primary key,                 -- ex. "Letoile", "Almet", "EMSO"
  actif      boolean not null default true,
  maj_at     timestamptz not null default now()
);

-- ---------- Familles (gérées par l'admin) ------------------------------
-- Regroupement de haut niveau des formes, tel que l'organigramme de l'atelier
-- l'utilise pour savoir quel fournisseur livre quoi (ex. "Tôles", "Barres", "Profilés").
create table if not exists public.mat_familles (
  nom        text primary key,
  actif      boolean not null default true,
  maj_at     timestamptz not null default now()
);

-- ---------- Formes (gérées par l'admin) -------------------------------
-- 'type' = type géométrique connu de l'appli (elle en déduit la formule de section) :
--   plat | rond | carre | tube_rond | tube_carre | tube_carre_eq | L | T | U | I | tole
-- 'famille' = regroupement (mat_familles.nom), sert à filtrer les formes proposées
-- à l'étudiant une fois la matière et la famille choisies.
create table if not exists public.mat_formes (
  nom        text primary key,                 -- ex. "Pavé (plat)", "Cylindre plein", "Profilé en I"
  type       text not null default 'plat',
  famille    text,
  actif      boolean not null default true,
  maj_at     timestamptz not null default now()
);
alter table public.mat_formes add column if not exists famille text;

-- ---------- Associations matière → fournisseur → famille (gérées par l'admin) --
-- Encode l'organigramme « quelle matière, livrée par quel fournisseur, pour quelle
-- famille » : ex. (Aluminium, EMSO, Barres), (Aluminium, Almet, Tôles ou Profilés).
-- Le fournisseur n'est jamais demandé à l'étudiant : déduit automatiquement de
-- (matière, famille) côté client (voir fournisseurFor() dans index.html).
create table if not exists public.mat_four_familles (
  id           bigint generated by default as identity primary key,
  fournisseur  text not null,
  matiere      text not null,
  famille      text not null,
  maj_at       timestamptz not null default now(),
  unique(fournisseur, matiere, famille)
);

-- ---------- Bruts proposés (section + longueur standard, par matière) ---
create table if not exists public.mat_bruts (
  id         bigint generated by default as identity primary key,
  matiere    text not null,
  forme      text not null,
  dims       jsonb not null default '{}'::jsonb,   -- ex. {"d":30} ou {"l":40,"e":10}
  longueur   numeric not null,                     -- longueur standard du brut, en mm
  masse_lin  numeric,                              -- kg/m facultatif (sinon calculé : section × densité)
  chute_min  numeric,                              -- colonne conservée mais plus modifiable depuis l'admin (simplifié) ;
                                                     -- le calcul utilise un seuil fixe de 100 mm (reste en dessous = perdu)
  actif      boolean not null default true,
  maj_at     timestamptz not null default now()
);
create index if not exists mat_bruts_mf_idx on public.mat_bruts (matiere, forme);

-- ---------- Dates de commande proposées par l'admin ---------------------
create table if not exists public.mat_dates (
  id            bigint generated by default as identity primary key,
  date_commande date not null,
  note          text default '',
  maj_at        timestamptz not null default now()
);

-- ---------- Budgets matière par parcours (distincts des composants) ------
create table if not exists public.mat_budgets (
  parcours   text primary key,
  limite     numeric,                          -- € pour l'année universitaire (null = pas de limite)
  maj_at     timestamptz not null default now()
);

-- ---------- Paramètres généraux ------------------------------------------
--   trait_scie    : épaisseur perdue à chaque coupe (mm) — reste de brut toujours considéré perdu
--                   (plus de notion de « reste réutilisable », simplifié depuis l'admin)
--   tva_taux      : taux de TVA (%) utilisé pour convertir un prix matière saisi HT en TTC
--   tole_longueur / tole_largeur : format standard d'une tôle (mm)
create table if not exists public.mat_parametres (
  cle        text primary key,
  valeur     text not null default '',
  maj_at     timestamptz not null default now()
);

-- ---------- Demandes de matière -------------------------------------------
create table if not exists public.mat_demandes (
  id                   bigint generated by default as identity primary key,
  created_at           timestamptz not null default now(),
  numero               integer default 0,             -- n° incrémental par projet

  -- Contexte (étudiant)
  projet               text not null default '',
  parcours             text not null default '',
  formation            text not null default '',
  etudiant_nom         text not null default '',
  etudiant_prenom      text not null default '',

  -- Pièce demandée
  matiere              text not null default '',
  famille              text default '',               -- Tôles | Barres | Profilés (ou vide si non déterminé)
  fournisseur          text default '',                -- déduit automatiquement de (matière, famille)
  forme                text not null default '',
  forme_type           text not null default '',
  dims                 jsonb not null default '{}'::jsonb,
  dims_libelle         text default '',               -- ex. "Ø30"
  longueur             numeric,                       -- mm, par pièce (longueur découpée)
  largeur              numeric,                       -- mm, uniquement pour une tôle (largeur découpée)
  quantite             integer not null default 1,
  hors_catalogue       boolean not null default false,
  notes                text default '',               -- usage / précisions de l'étudiant
  precision_etudiant   text default '',               -- précisions ajoutées après une mise en attente

  -- Instantané de l'estimation (les prix peuvent changer ensuite)
  densite              numeric,
  prix_kg              numeric,
  masse_lin            numeric,
  poids_kg             numeric,                       -- poids total des pièces
  cout_matiere         numeric,                       -- € de matière utilisée (= ce qui est débité du budget)
  brut_desc            text default '',               -- ex. "Acier S235 · Cylindre plein Ø30 · 3000 mm"
  brut_longueur        numeric,
  brut_qte             integer default 1,
  part_brut            numeric,                       -- portion du brut utilisée (0–1)
  perdu_mm             numeric,                       -- longueur perdue (trait de scie + chute inutilisable)
  cout_perte           numeric,                       -- € de matière perdue (information)
  reste_mm             numeric,                       -- reste de brut

  -- Décision encadrant
  statut               text not null default 'en_attente',
    -- en_attente | attente_info | validee | commandee | recue | remise | refusee | annulee
  decision             text,                          -- 'stock' (dispo, réservée atelier) | 'commande' (à commander)
  date_commande        date,                          -- date de commande retenue (si decision = 'commande')
  encadrant_nom        text default '',
  encadrant_at         timestamptz,
  encadrant_commentaire text default '',
  encadrant_commentaire_at timestamptz,

  -- Suivi (géré par le gestionnaire)
  gest_nom             text default '',
  gest_commentaire     text default '',
  commandee_at         timestamptz,
  recue_at             timestamptz,
  remise_at            timestamptz,
  statut_at            timestamptz default now(),

  historique           jsonb not null default '[]'::jsonb   -- [{t, statut, par}]
);
create index if not exists mat_demandes_statut_idx on public.mat_demandes (statut);
create index if not exists mat_demandes_projet_idx on public.mat_demandes (lower(projet));
create index if not exists mat_demandes_created_idx on public.mat_demandes (created_at);

-- ---------- Valeurs de départ ----------------------------------------------
-- Densités = constantes physiques usuelles. Les PRIX AU KILO sont volontairement laissés vides :
-- c'est l'admin qui les renseigne (Admin → Matières). Idem pour les bruts proposés.
insert into public.mat_matieres (nom, densite, prix_kg) values
  ('Acier S235',        7.85, null),
  ('Acier inoxydable',  7.90, null),
  ('Aluminium',         2.70, null),
  ('Laiton',            8.50, null)
on conflict (nom) do nothing;

insert into public.mat_familles (nom) values
  ('Tôles'), ('Barres'), ('Profilés')
on conflict (nom) do nothing;

insert into public.mat_fournisseurs (nom) values
  ('Letoile'), ('Almet'), ('EMSO')
on conflict (nom) do nothing;

-- Formes = la liste « Famille / Type / Dimensions » de l'organigramme de l'atelier.
-- 'T', 'U', 'I' (profilés en T/U/I) restent définis dans l'appli (FORME_TYPES) mais ne sont
-- plus pré-créés ici : ajoutez-les depuis Admin → Formes si besoin.
insert into public.mat_formes (nom, type, famille) values
  ('Tôle',                           'tole',          'Tôles'),
  ('Ronde',                          'rond',          'Barres'),
  ('Carré',                          'carre',         'Barres'),
  ('Méplat',                         'plat',          'Barres'),
  ('Tubes rond',                     'tube_rond',     'Profilés'),
  ('Tubes carrés',                   'tube_carre_eq', 'Profilés'),
  ('Tubes rectangulaires',           'tube_carre',    'Profilés'),
  ('Cornière',                       'L',             'Profilés'),
  ('Plat',                           'plat',          'Profilés')
on conflict (nom) do nothing;

-- Associations matière → fournisseur → famille (organigramme 1 de l'atelier).
insert into public.mat_four_familles (fournisseur, matiere, famille) values
  ('Letoile', 'Acier S235',       'Tôles'),
  ('Letoile', 'Acier S235',       'Barres'),
  ('Letoile', 'Acier S235',       'Profilés'),
  ('Almet',   'Aluminium',        'Tôles'),
  ('Almet',   'Aluminium',        'Profilés'),
  ('EMSO',    'Aluminium',        'Barres'),
  ('Almet',   'Acier inoxydable', 'Barres'),
  ('Almet',   'Acier inoxydable', 'Profilés'),
  ('EMSO',    'Acier inoxydable', 'Tôles')
on conflict (fournisseur, matiere, famille) do nothing;
-- (Laiton et toute nouvelle matière n'ont volontairement aucune association : l'étudiant
--  verra alors toutes les formes actives, sans fournisseur déduit — « ça dépend », à
--  confirmer par l'atelier. Ajoutez les associations depuis Admin → Fournisseurs & familles.)

insert into public.mat_parametres (cle, valeur) values
  ('trait_scie',    '3'),
  ('tva_taux',      '20'),
  ('tole_longueur', '2000'),
  ('tole_largeur',  '1000')
on conflict (cle) do nothing;

-- ---------- Sécurité (RLS) — lecture publique, écritures via Edge Function ----------
-- Le public LIT les tables mat_* ; toutes les ÉCRITURES passent par l'Edge Function « matiere-op »
-- (clé service, qui contourne la RLS, droits vérifiés côté serveur). Aucune policy INSERT/UPDATE/DELETE
-- = refus total pour la clé anon. (Déployer matiere-op AVANT de s'en servir : voir README.)
alter table public.mat_matieres enable row level security;
alter table public.mat_fournisseurs enable row level security;
alter table public.mat_familles enable row level security;
alter table public.mat_formes enable row level security;
alter table public.mat_four_familles enable row level security;
alter table public.mat_bruts enable row level security;
alter table public.mat_dates enable row level security;
alter table public.mat_budgets enable row level security;
alter table public.mat_parametres enable row level security;
alter table public.mat_demandes enable row level security;

drop policy if exists mat_matieres_all on public.mat_matieres;
drop policy if exists mat_matieres_sel on public.mat_matieres;
create policy mat_matieres_sel on public.mat_matieres for select using (true);
drop policy if exists mat_fournisseurs_all on public.mat_fournisseurs;
drop policy if exists mat_fournisseurs_sel on public.mat_fournisseurs;
create policy mat_fournisseurs_sel on public.mat_fournisseurs for select using (true);
drop policy if exists mat_familles_all on public.mat_familles;
drop policy if exists mat_familles_sel on public.mat_familles;
create policy mat_familles_sel on public.mat_familles for select using (true);
drop policy if exists mat_formes_all on public.mat_formes;
drop policy if exists mat_formes_sel on public.mat_formes;
create policy mat_formes_sel on public.mat_formes for select using (true);
drop policy if exists mat_four_familles_all on public.mat_four_familles;
drop policy if exists mat_four_familles_sel on public.mat_four_familles;
create policy mat_four_familles_sel on public.mat_four_familles for select using (true);
drop policy if exists mat_bruts_all on public.mat_bruts;
drop policy if exists mat_bruts_sel on public.mat_bruts;
create policy mat_bruts_sel on public.mat_bruts for select using (true);
drop policy if exists mat_dates_all on public.mat_dates;
drop policy if exists mat_dates_sel on public.mat_dates;
create policy mat_dates_sel on public.mat_dates for select using (true);
drop policy if exists mat_budgets_all on public.mat_budgets;
drop policy if exists mat_budgets_sel on public.mat_budgets;
create policy mat_budgets_sel on public.mat_budgets for select using (true);
drop policy if exists mat_parametres_all on public.mat_parametres;
drop policy if exists mat_parametres_sel on public.mat_parametres;
create policy mat_parametres_sel on public.mat_parametres for select using (true);
drop policy if exists mat_demandes_all on public.mat_demandes;
drop policy if exists mat_demandes_sel on public.mat_demandes;
create policy mat_demandes_sel on public.mat_demandes for select using (true);

-- ---------- Temps réel (rafraîchissement des écrans) -------------------------
do $$
begin
  begin alter publication supabase_realtime add table public.mat_demandes;      exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.mat_matieres;      exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.mat_fournisseurs;  exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.mat_familles;      exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.mat_formes;        exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.mat_four_familles; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.mat_bruts;         exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.mat_dates;         exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.mat_budgets;       exception when duplicate_object then null; end;
end $$;
