-- =====================================================================
--  Commandes d'éléments standards — schéma à coller dans le SQL Editor de Supabase
--  (MÊME projet que reservation-machines / impression 3D : ggmlfbxppgeivfvlxxrj)
--
--  Ce script AJOUTE trois tables (commandes, com_fournisseurs, com_budgets).
--  Il ne supprime ni ne modifie aucune donnée ni aucune table existante.
--  On peut le relancer sans risque (IF NOT EXISTS partout).
--
--  ⚠️ PHASE TEST : les 3 tables sont en écriture directe (policy permissive),
--  comme l'était la table 'demandes' au début. Au passage en version publique,
--  on remplacera ces policies par des Edge Functions (voir README.md).
-- =====================================================================

-- ---------- Table des lignes de commande -----------------------------
create table if not exists public.commandes (
  id                   bigint generated by default as identity primary key,
  created_at           timestamptz not null default now(),
  numero               integer default 0,            -- n° incrémental par groupe (indicatif)

  -- Contexte de la demande (rempli par l'encadrant)
  formation            text not null default '',     -- ex. "BUT 2 Init", "BUT 3 App"
  parcours             text not null default '',     -- ex. "II", "CPD", "SNRV"
  groupe               text not null default '',     -- sujet / groupe projet
  encadrant            text not null default '',     -- encadrant demandeur

  -- Article
  fournisseur          text not null default '',
  intitule             text not null default '',     -- intitulé & description
  reference            text default '',
  lien                 text default '',              -- lien web produit
  quantite             numeric default 1,
  cout_unitaire        numeric,                      -- prix unitaire estimé (facultatif)
  cout_total           numeric,                      -- coût total de la ligne (estimé puis ajusté par le gestionnaire)

  -- Suivi (géré par le gestionnaire)
  statut               text not null default 'demandee',
    -- demandee | commandee | recue_partielle | recue_complete | remise | refusee | annulee
  recue_note           text default '',              -- "complet" | "partiel" | texte libre
  commandee_at         timestamptz,
  recue_at             timestamptz,
  remise_at            timestamptz,

  -- Échanges
  commentaire_demandeur   text default '',
  commentaire_gestionnaire text default '',

  historique           jsonb not null default '[]'::jsonb  -- [{t, statut, par}]
);

alter table public.commandes add column if not exists numero                  integer default 0;
alter table public.commandes add column if not exists cout_unitaire           numeric;
alter table public.commandes add column if not exists cout_total              numeric;
alter table public.commandes add column if not exists recue_note              text default '';
alter table public.commandes add column if not exists commandee_at            timestamptz;
alter table public.commandes add column if not exists recue_at                timestamptz;
alter table public.commandes add column if not exists remise_at               timestamptz;
alter table public.commandes add column if not exists commentaire_demandeur   text default '';
alter table public.commandes add column if not exists commentaire_gestionnaire text default '';
alter table public.commandes add column if not exists historique              jsonb not null default '[]'::jsonb;

create index if not exists commandes_statut_idx    on public.commandes (statut);
create index if not exists commandes_groupe_idx    on public.commandes (lower(groupe));
create index if not exists commandes_parcours_idx  on public.commandes (parcours);
create index if not exists commandes_fournisseur_idx on public.commandes (lower(fournisseur));
create index if not exists commandes_created_idx   on public.commandes (created_at);

-- ---------- Table des fournisseurs (liste gérée en Admin) -----------
create table if not exists public.com_fournisseurs (
  nom        text primary key,
  site       text default '',
  delai      text default '',            -- délai indicatif ("48 h", "1 semaine"...)
  notes      text default '',
  actif      boolean not null default true,
  cree_at    timestamptz not null default now()
);

-- ---------- Table des budgets par parcours -------------------------
create table if not exists public.com_budgets (
  parcours   text primary key,
  limite     numeric,                    -- limite en € pour l'année universitaire (null = pas de limite)
  maj_at     timestamptz not null default now()
);

-- ---------- Gestionnaires (opérateurs habilités à gérer les commandes) ----
-- Ne stocke QUE le nom : le code opérateur reste dans la table verrouillée 'operateurs'
-- et est vérifié par l'Edge Function 'verify-code'. Cette table sert juste à filtrer
-- la liste déroulante du portail « Espace gestionnaire ». Si la table est vide,
-- l'appli propose tous les opérateurs (repli).
create table if not exists public.com_gestionnaires (
  nom       text primary key,
  cree_at   timestamptz not null default now()
);

-- ---------- Fournisseurs pré-remplis (d'après le tableau existant) --
insert into public.com_fournisseurs (nom, site) values
  ('HPC',                 'https://shop.hpceurope.com'),
  ('Michaud Chailly',     'https://www.michaud-chailly.fr'),
  ('FixNVis',             'https://www.visseriefixations.fr'),
  ('norelem',             'https://www.norelem.fr'),
  ('123 Roulement',       'https://www.123roulement.com'),
  ('Sodemann',            'https://www.ressorts-sodemann.fr'),
  ('Technic-Achat',       'https://www.technic-achat.com'),
  ('Leroy Merlin',        'https://www.leroymerlin.fr'),
  ('Amazon',              'https://www.amazon.fr'),
  ('TLB Golf',            ''),
  ('PRP Machines',        'https://prp-machines.fr'),
  ('RemorqueShop',        'https://www.remorqueshop.fr'),
  ('VisExpress',          ''),
  ('Autre (préciser)',    '')
on conflict (nom) do nothing;

-- ---------- Sécurité (RLS) — PHASE TEST : écriture directe anon -----
alter table public.commandes         enable row level security;
alter table public.com_fournisseurs  enable row level security;
alter table public.com_budgets       enable row level security;
alter table public.com_gestionnaires enable row level security;

drop policy if exists commandes_all on public.commandes;
create policy commandes_all on public.commandes
  for all using (true) with check (true);

drop policy if exists com_fournisseurs_all on public.com_fournisseurs;
create policy com_fournisseurs_all on public.com_fournisseurs
  for all using (true) with check (true);

drop policy if exists com_budgets_all on public.com_budgets;
create policy com_budgets_all on public.com_budgets
  for all using (true) with check (true);

drop policy if exists com_gestionnaires_all on public.com_gestionnaires;
create policy com_gestionnaires_all on public.com_gestionnaires
  for all using (true) with check (true);

-- ---------- Temps réel (rafraîchissement des écrans) ---------------
do $$
begin
  begin alter publication supabase_realtime add table public.commandes;         exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.com_fournisseurs;  exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.com_budgets;       exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.com_gestionnaires; exception when duplicate_object then null; end;
end $$;
